parser: babel-eslint

extends:
    - eslint:recommended
    - plugin:react/recommended
    - prettier

env:
    node: true
    es6: true

parserOptions:
    sourceType: module
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true

plugins:
    - import

rules:
    semi: [2, never]
    lines-around-directive: 0
    arrow-parens: 0
    no-use-before-define: 0
    no-unused-vars: 1
    no-redeclare: 0
    object-curly-spacing: 0
    no-console: 0
    dot-notation: 0
    strict: 0
    comma-dangle: 0
    react/prop-types: 0
