module.exports.isDir = require('./is-dir')
module.exports.checkEnvVars = require('./check-env-vars')
module.exports.exif = require('./exif')
module.exports.stripext = require('./strip-ext')
module.exports.getExifYear = require('./get-exif-year')
module.exports.isJpeg = require('./is-jpeg')
module.exports.getInfoFromImage = require('./get-info-from-image')
